// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DataSeeding.Data;

#nullable disable

namespace DataSeeding.DataSeeding.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Models.School", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elminya School"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cairo School"
                        },
                        new
                        {
                            Id = 3,
                            Name = "New Minya School"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alex School"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aswaan School"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Giza School"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Assiut School"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Models.Student", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Liam",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Noah",
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oliver",
                            SchoolId = 4
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elijah",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "William",
                            SchoolId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "James",
                            SchoolId = 7
                        },
                        new
                        {
                            Id = 7,
                            Name = "Benjamin",
                            SchoolId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lucas",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Henry",
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Alexander",
                            SchoolId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mason",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Michael",
                            SchoolId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ethan",
                            SchoolId = 7
                        },
                        new
                        {
                            Id = 14,
                            Name = "Daniel",
                            SchoolId = 6
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jacob",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Models.Student", b =>
                {
                    b.HasOne("EntityFrameworkCore.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EntityFrameworkCore.Models.School", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
